### ISSUE TITLE
Add to an empty group - 500

### ISSUE THREAD

**Issue by an0key** [emfcamp/numbermanagement#15]
If I try to navigate to https://phones.emfcamp.org/group/5853 and hit add, the group has no members, I get a 500 error. 

I think this is due to ---- being selected in the group first, and clicking add, trys to add that number... works fine if I select one of the extensions from the dropdown

**Comment by sammachin** [comment]
ah yes UX bug, that dropdown is pretty knarly and we'd like to improve it

**Comment by sammachin** [comment]
easiest fix would be to disable the add button if a number isn't selected

**Comment by sammachin** [comment]
fixed in #18 
![image](https://github.com/emfcamp/numbermanagement/assets/187645/b77261a3-18a1-47e5-9b94-81d70e9cf5ae)
