### ISSUE TITLE
Details page for APP numbers 500s (if app doesnt exist?)

### ISSUE THREAD

**Issue by MattGrayYes** [emfcamp/numbermanagement#7]
go to my numbers
click details on an app

**Comment by sammachin** [comment]
Created an app page,
But we should update the tempalte logic so if there isn't a [TypeOfService].html file it just renders a geneic page with the number & param

**Comment by sammachin** [comment]
fixed in https://github.com/emfcamp/numbermanagement/commit/af39285d17d71bc448cc8cb45ed85ab19bc20d57
